### ISSUE TITLE
Changes in biblatex 3.8

### ISSUE THREAD

**Issue by moewew** [maieul/biblatex-realauthor#7]
`biblatex` 3.8 is ready to be released hopefully quite soon.

Some of the changes are going to affect your packages, `biblatex-realauthor` should be affected by the name change from `\DeclareSortingScheme` to `\DeclareSortingTemplate`. The old name should continue to work, but will cause a warning.

The full list of changes is at https://github.com/plk/biblatex/blob/dev/doc/latex/biblatex/CHANGES.org and https://github.com/plk/biblatex/wiki

**Comment by maieul** [comment]
I will do a release after the relase. I prefer install new version of biblatex with tlgmr than manually

**Comment by moewew** [comment]
Since the changes should not break your styles you don't have to hurry. The worst thing that should happen is a few warnings.

I didn't post a separate issue at the respective bug trackers, but `biblatex-manuscripts-philology` and `biblatex-shortfields` are also affected.
